---
title: "Cut&Run analysis"
author: ""
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: 
    html_document:
        toc: TRUE
        toc_float: FALSE
        toc_depth: 2
        toc_collapsed: FALSE
        theme: readable
        number_sections: FALSE
        coding_folding: hide
        code_download: FALSE
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
params:
  dat.dir: "./"
---

```{r setup, include=FALSE, dev='CairoPNG'}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning=FALSE, dev="CairoPNG")
# knitr::opts_knit$set(root.dir = params$dat.dir)

options(stringsAsFactors = F)
options(scipen = 99)
library(Cairo)
library(ggplot2)
library(dplyr)
library(patchwork)
library(kableExtra)

```


## Summary

This document presents analysis results of Cut & Run or Cut & Tag data.

$$\\[0.5in]$$

## {.unnumbered .unlisted}

```{r make_tabs, include=FALSE}
# Function to create multiple tabs
make_tabs <- function(title, contents){
  cat(title, "\n\n")
  for (cnt in contents){print(cnt); cat("\n")}
  cat("\n\n")
}
```

```{r plot_functions}

dot_plot <- function(df, var.x = 'bt2_total_reads_target', var.y = 'sample_group', var.color = 'sample_replicate', xlab = 'Total reads (in million)', ylab = '', color = 'Replicate', plot.title = 'Sequenced reads', scale_x = 1){
  require(ggplot2)
  
  
  if (nrow(df) == 0){ 
    return(
      ggplot(data.frame(x=0,y=0))+
        geom_blank()+
        theme_minimal()
    ) 
  }
  
  
  as.data.frame(df) %>% 
    mutate(x = df[,var.x] * scale_x, y = df[,var.y], color = factor(df[, var.color])) %>% 
    ggplot(mapping = aes(x = x, y = y, color = color))+
    geom_jitter(height = 0.1, width = 0)+
    labs(x = xlab, y = ylab, color = color, title = plot.title)+
    theme_bw()+
    theme(
      plot.margin = unit(rep(0.1,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )
  
}

dot_plot2 <- function(df, var.x = 'npeak', var.y = 'sample_group', var.color = 'toIgG', add_facet = facet_grid(~caller, scales = 'free'), var.shape = 'filtered', xlab = 'Total Peaks (in thousand)', ylab = '', scale_color = scale_color_manual('', values = c("IgG_controlled"="indianred", "Target_only"="steelblue")),       scale_shape, shape = '', plot.title = 'Peaks from each sample', scale_x = 1){
    require(ggplot2)
    
    if (nrow(df) == 0){ 
      return(
        ggplot(data.frame(x=0,y=0))+
          geom_blank()+
          theme_minimal()
      ) 
    }
    
    
    as.data.frame(df) %>% 
      mutate(x = df[,var.x]*scale_x, y = df[,var.y], color = df[,var.color], shape = df[,var.shape]) %>% 
      ggplot(mapping = aes(x = x, y = y, color = color, shape = shape))+
      geom_jitter(height = 0.1, width = 0)+
      add_facet+
      scale_color+
      scale_shape+
      labs(
        x = xlab, y = ylab, 
        shape = shape, title = plot.title)+
    theme_bw()+
    theme(
      plot.margin = unit(rep(0.1,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )

  }

density_plot <- function(df, var.x = 'length', var.y = 'count', var.group = 'id', var.color = 'sample_replicate', facet.row = 'sample_group', xlab = 'Fragment length (bp)', ylab = 'Occurrences', color = 'Replicate', plot.title = 'Fragment length'){
    require(ggplot2)
    
    if (nrow(df) == 0){ 
      return(
        ggplot(data.frame(x=0,y=0))+
          geom_blank()+
          theme_minimal()
      ) 
    }
    
    
    df <- as.data.frame(df)
    p <- df %>%
      mutate(x = df[,var.x], y = df[,var.y], group = df[,var.group], color = factor(df[,var.color]), facet.row = df[,facet.row]) %>%
      ggplot(mapping = aes(x=x, y=y, group = group, color = color))+
      geom_line(size=0.5)+
      labs(x=xlab, y=ylab, color=color, title = plot.title)+
    theme_bw()+
    theme(
      plot.margin = unit(rep(0.1,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )
    
    if (length(unique(df$sample_group)) > 1){
      p+ 
        facet_grid(facet.row ~ .)
    }else{
      p
    }
  }

violin_plot <- function(df, var.x = 'length', var.y = 'id', var.color = 'caller', xlab = 'Peak Width (bp)', ylab = '', scale_color = scale_color_manual('', values = c(SEACR='darkblue', MACS2narrow='red', MACS2broad='brown')), plot.title = 'Peak width'){
    require(ggplot2)
    
    if (nrow(df) == 0){ 
      return(
        ggplot(data.frame(x=0,y=0))+
          geom_blank()+
          theme_minimal()
      ) 
    }
    
    ## determine data range
    length.max <- as.data.frame(df) %>% 
      group_by(sample_group, caller) %>% 
      reframe(
        qt = quantile(length, 0.75)
      ) %>% 
      reframe(
        max = max(qt)
      ) %>% 
      as.matrix() %>% 
      as.vector()
    
    ## make plots
    as.data.frame(df) %>% 
      mutate(x = .[,var.x], y = .[,var.y], color = .[,var.color]) %>% 
      ggplot(mapping = aes(x = x, y = y, color = color, weight = weight))+
      geom_violin(bw=5, trim = T, draw_quantiles = 0.5, orientation = 'y')+
      scale_color+
      coord_cartesian(xlim = c(0, length.max))+
      labs(x=xlab, y=ylab, title = plot.title)+
    theme_bw()+
    theme(
      plot.margin = unit(rep(0.1,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )

  }

violin_plot2 <- function(
  df, 
  var.x = 'length', var.y = 'id', var.color = 'color', var.facet.col = 'caller',
  xlab = 'Peak Width (bp)', ylab = '', plot.title = 'Peak width'
){
    require(ggplot2)
    
    if (nrow(df) == 0){ 
      return(
        ggplot(data.frame(x=0,y=0))+
          geom_blank()+
          theme_minimal()
      ) 
    }
    
    df <- df %>% 
      mutate(x = .[,var.x], y = .[,var.y], color = .[,var.color], facet.col = .[,var.facet.col]) %>% 
      as.data.frame()
    
    ## make plots
    plist <- lapply(
      split(df, df[,var.facet.col]),
      function(x){
        x %>% 
          ggplot(mapping = aes(x = x, y = y, color = color, weight = weight))+
          geom_violin(bw=5, trim = T, draw_quantiles = 0.5, orientation = 'y')+
          scale_y_discrete(drop = F)+
          scale_color_identity()+
          coord_cartesian(xlim = as.vector(quantile(x$x, c(0,0.75))))+
          labs(x=xlab, y=ylab, color='', title = plot.title, subtitle = x$facet.col[1])+
          theme_bw()+
          theme(
            plot.margin = unit(rep(0.1,4), 'line'),
            plot.title = element_text(size = 10),
            axis.text = element_text(size = 10),
            axis.title = element_text(size = 10),
            legend.text = element_text(size = 8),
            legend.title = element_text(size = 8),
            axis.text.x = element_text(angle = 45, hjust = 1),
            strip.text.y = element_text(angle = 0),
            legend.position = 'top'
          )
      })
    if(length(plist) > 1){
      plist[2:length(plist)] <- lapply(
        plist[2:length(plist)], function(p){
          p+
            theme(
              axis.text.y = element_blank(),
              axis.ticks.y = element_blank()
            )
        }
      )
    }
    
    return(plist)
}


bar_plot <- function(df, var.y = 'sample_group', var.fill = 'shared', xlab = 'peak count', ylab = '', color = 'Replicate', plot.title = 'Sequenced reads', scale_x = 1){
  require(ggplot2)
  
  if (nrow(df) == 0){ 
    return(
      ggplot(data.frame(x=0,y=0))+
        geom_blank()+
        theme_minimal()
    ) 
  }
  
  
  as.data.frame(df) %>% 
    mutate(y = df[,var.y], fill = df[,var.fill]) %>% 
    ggplot(aes(y = y, fill = factor(fill)))+
    geom_bar()+
    scale_x_continuous(expand = c(0,0))+
    labs(y = ylab, x = xlab, fill = '', title = plot.title)+
    theme_bw()+
    theme(
      plot.margin = unit(rep(0.1,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      legend.key.height = unit(1, 'line'),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )
  
}

bar_plot2 <- function(df, var.y = 'genomic.location', xlab = 'Consensus peak count', ylab = '', plot.title = ''){
    require(dplyr)
    require(ggplot2)
    
    if (nrow(df) == 0){ 
      return(
        ggplot(data.frame(x=0,y=0))+
          geom_blank()+
          theme_minimal()
      ) 
    }
    
    df %>% 
      mutate(y = df[,var.y]) %>% 
      as.data.frame() %>% 
      ggplot(aes(y = y))+
      geom_bar()+
      scale_x_continuous(expand = c(0,0))+
      labs(x = xlab, y = ylab, title = plot.title)+
          theme_bw()+
    theme(
      plot.margin = unit(rep(0.5,4), 'line'),
      plot.title = element_text(size = 10),
      axis.text = element_text(size = 10),
      axis.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1),
      strip.text.y = element_text(angle = 0),
      legend.position = 'top'
    )

    
  }

venn_plot <- function(mtx, plot.title = ''){
    venn::venn(
      mtx,
      ggplot = T,
      box = F,
      par = par(mar = rep(0.1,4), cex = 1.5)
    )+
      labs(title = plot.title)+
      theme(
        text = element_text(size = 12),
        plot.margin = unit(rep(0.1, 4), 'line'),
        plot.title = element_text(size = 12)
      )
    
  }

plot_pca <- function(y, out.prefix = 'pca', var.genes = NULL, color = NULL, plot.title = '', sample.label = T, feature.length = 'gene_length', save.plot = F){
    options(stringsAsFactors = F)
    require(ggrepel)
    require(edgeR)
    
    log2rpkm <- rpkm(y, gene.length = feature.length, normalized.lib.sizes = T, log = T)
    
    if (!is.null(var.genes)){
        keep <- rank(-apply(log2rpkm, 1, var)) < var.genes
        log2rpkm <- log2rpkm[keep,]
    }
    
    ## Run PCA
    pca <- prcomp(t(log2rpkm), center = T, scale = T)
    
    ## Scree plot
    pca.variance.prop <- (pca$sdev^2)/sum(pca$sdev^2)*100
    
    ## PC1 vs PC2
    df <- cbind(pca$x[,1:2],data.frame(label=rownames(pca$x)))
    if(is.null(color)){
        df$color <- y$samples$group
    }else{
        df$color <- color
    }
    
    if(length(unique(df$color))>1){
        p <- ggplot(df,aes(x=PC1,y=PC2,label=label,color=color))
    }else{
        p <- ggplot(df,aes(x=PC1,y=PC2,label=label))
    }
    p <- p +
        geom_point(shape = 1)
    
    if(sample.label){
        p <- p +
            geom_text_repel(size = 2.4, color = 'black', position = 'jitter',max.overlaps = 80)
    }
    
    p <- p +
        labs(
            title = plot.title,
            color = '', 
            x = paste0('PC1 (',round(pca.variance.prop[1],1),'%)'),
            y = paste0('PC2 (',round(pca.variance.prop[2],1),'%)')
        )+
      theme_bw()+
      theme(
        plot.margin = unit(rep(0.1,4), 'line'),
        plot.title = element_text(size = 10),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        axis.text.x = element_text(angle = 90, hjust = 1),
        strip.text.y = element_text(angle = 0),
        legend.position = 'top'
      )
    
    if (save.plot){ 
      ## Create outdir if needed
      out.dir <- dirname(out.prefix)
      if(!dir.exists(out.dir)){dir.create(out.dir,recursive = T)
      }
      
ggsave(paste(out.prefix,'PCA.pdf',sep='.'),width = 5,height = 5)}
    
    ## return data
    return(p)
    
}

## Plot MD
plot_MD <- function(df, out.prefix = 'md', plot.title = "", save.plot = F){
    require(ggplot2)
    
    p <- ggplot(df, aes(x = logCPM, y = logFC, color=factor(is.sig)))+
        geom_hline(yintercept = 0)+
        geom_point(size = 0.2)+
        scale_color_manual(
            '',
            values = c("-1" = "blue", "0" = "gray", "1" = "red"),
            breaks = c(-1,0,1), labels = c('Down', 'No Sig.', 'Up')
        )+
        labs( 
            x = "Average log CPM", 
            y = "log-fold-of-change",
            title = plot.title
        )+
        theme_bw()+
      theme(
        plot.margin = unit(rep(0.1,4), 'line'),
        plot.title = element_text(size = 10),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        axis.text.x = element_text(angle = 90, hjust = 1),
        strip.text.y = element_text(angle = 0),
        legend.position = 'top'
      )
    
    if (save.plot){
      ## Create outdir if needed
      out.dir <- dirname(out.prefix)
      if(!dir.exists(out.dir)){dir.create(out.dir,recursive = T)}
      ggsave(paste(out.prefix,'MD.pdf',sep = '.'),width = 4,height = 5)
    }
    
    return(p)
} 

## Plot volcano 
plot_volcano <- function(df, out.prefix = 'volcano', plot.title = "", save.plot = F){
    require(ggplot2)
    
    p <- ggplot(df,aes(x=logFC,y=-log10(FDR),color=factor(is.sig)))+
        geom_point(size = 0.2)+ 
        scale_color_manual(
            values = c('-1'='blue','0'='gray','1'='red'),
            breaks = c('-1','0','1'),
            labels = c('Down','No Sig.','Up'),
            drop = T
        )+
        labs(
            x='log2(fold change)',
            y='-log10(FDR)',
            color='',
            title = plot.title
        )+
        theme_bw()+
      theme(
        plot.margin = unit(rep(0.1,4), 'line'),
        plot.title = element_text(size = 10),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        axis.text.x = element_text(angle = 90, hjust = 1),
        strip.text.y = element_text(angle = 0),
        legend.position = 'top'
      )
    
    if (save.plot){
      ## Create outdir if needed
      out.dir <- dirname(out.prefix)
      if(!dir.exists(out.dir)){dir.create(out.dir,recursive = T)}
      ggsave(paste(out.prefix,'Volcano.pdf',sep = '.'),width = 4,height = 5)
      
    }
    
    return(p)
}

```

```{r read_input}
dat <- readRDS('data.rds')
ss <- dat$ss
meta <- dat$meta
targets <- sort(setdiff(unique(meta$target), c('IgG', 'Input'))) # targets to make QC plots

figs <- list()

```

```{r read_plots}
## Total sequened reads ####
if ('bt2_total_reads_target' %in% colnames(meta)){
  qc <- 'seq_depth'
  figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'bt2_total_reads_target', var.y = 'sample_group', xlab = 'Total reads (in million)', ylab = '', color = 'Replicate', plot.title = 'Sequenced reads', scale_x = 1e-6)
}


## Aligned reads to the target genome ####
if ('bt2_total_aligned_target' %in% colnames(meta)){
    qc <- 'aligned_reads'
      figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'bt2_total_aligned_target', var.y = 'sample_group', xlab = 'Aligned reads (in million) ', ylab = '', color = 'Replicate', plot.title = 'Reads aligned to target genome', scale_x = 1e-6)
    
  }  
  
## Alignment rate to the target genome ####
if ('bt2_overall_alignment_rate_target' %in% colnames(meta)){
    qc <- 'aligned_pct' 
    figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'bt2_overall_alignment_rate_target', var.y = 'sample_group', xlab = 'Fraction of reads aligned', ylab = '', color = 'Replicate', plot.title = 'Alignment rate to target genome', scale_x = 1)
    
  }  
## Aligned reads to spike-in genome ####
  if ('bt2_overall_alignment_rate_spikein' %in% colnames(meta)){
    qc <- 'aligned_reads_spikein'
    figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'bt2_total_aligned_spikein', var.y = 'sample_group', xlab = 'Aligned reads (in thousand)', ylab = '', color = 'Replicate', plot.title = 'Reads aligned to spike-in genome', scale_x = 1e-3)
    
  }
  
## Duplication rate ####
  if ('dedup_percent_duplication' %in% colnames(meta)){
    qc <- 'dup_rate'
    figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'dedup_percent_duplication', var.y = 'sample_group', xlab = 'Duplication Rate', ylab = '', color = 'Replicate', plot.title = 'Duplication rate', scale_x = 1)

  }
  
## Estimated library size ####
  if ('dedup_estimated_library_size' %in% colnames(meta)){
    qc <- 'est_lib_size' 
    figs[[qc]] <- lapply(
    split(meta, meta$target),
    dot_plot, 
    var.x = 'dedup_estimated_library_size', var.y = 'sample_group', xlab = 'library size (in million)', ylab = '', color = 'Replicate', plot.title = 'Estimated library size', scale_x = 1e-6)
  }  
  
## Fragment lengths ####  
qc <- 'frag_lens'
if (qc %in% names(dat)){
figs[[qc]] <- lapply(
    split(dat$frag_lens, dat$frag_lens$target), 
    density_plot, 
    var.x = 'length', var.y = 'count', var.group = 'id', facet.row = 'sample_group', xlab = 'Fragment length (bp)', ylab = 'Occurrences', color = 'Replicate', plot.title = 'Fragment length'
  )
}

```

```{r ori_peak_plots}
## Original peak counts ####
if ('npeaks' %in% names(dat)){
  qc <- 'count_peaks' 
  figs[[qc]] <- lapply(
    split(dat$npeaks, dat$npeaks$target), 
    dot_plot2,
    var.x = 'npeak', var.y = 'id', var.color = 'toIgG', add_facet = facet_grid(~caller, scales = 'free'), var.shape = 'filtered', xlab = 'Total Peaks (in thousand)', ylab = '', scale_color = scale_color_manual('', values = c("IgG_controlled"="indianred", "Target_only"="steelblue")), scale_shape = scale_shape_manual(values = c(filtered=19, unfiltered=1)), shape = '', plot.title = 'Peaks from each sample', scale_x = 1e-3)
}

## Final peak widths ####
if ('wpeaks' %in% names(dat)){
  qc <- 'peak_width'
  figs[[qc]] <- lapply(
    split(dat$wpeaks, dat$wpeaks$target), 
    function(df){
      df <- df %>% 
        mutate(
          id = factor(id),
          color = plyr::mapvalues(caller, from = c('SEACR', 'MACS2narrow', 'MACS2broad'), to = c('darkblue', 'red', 'brown')) 
        )
      
      wrap_plots(violin_plot2(df, var.color = 'color', plot.title = ''), nrow = 1, guides = 'collect')+
        plot_annotation(title = 'Peak_width')
      
    })
}

## Reads in peak ####
if ('frip' %in% names(dat)){
    qc <- 'peak_frip'
  figs[[qc]] <- lapply(
    split(dat$frip, dat$frip$target), 
    dot_plot2, 
    var.x = 'FRiP', var.y = 'id', var.color = 'caller', var.shape = 'filtered', add_facet = NULL, xlab = 'Fraction of reads in peak', ylab = '', scale_color = scale_color_manual('', values = c(SEACR='darkblue', MACS2narrow='red', MACS2broad='brown')), scale_shape = scale_shape_manual('', values = c(filtered = 1, unfiltered = 2)), plot.title = 'Fraction of reads in peak', scale_x = 1)
  

}
```

```{r rep_peak_plots}
if ('nreps' %in% names(dat)){
  qc <- 'count_reps'
  
  npeaks <- dat$npeaks %>% 
    mutate(
      peak_type = paste(toIgG, filtered, sep = '_'),
      sample_replicate = paste0('replicate', sample_replicate)
      ) %>% 
    dplyr::select(id, target, sample_group, caller, peak_type, sample_replicate, npeak)
  
  ## combine replicated peaks and original peaks
  df <- bind_rows(
    bind_rows(
    lapply(
    split(npeaks, paste(npeaks$id, npeaks$caller)),
    function(x){
      if(sum(grepl('_filtered', x$peak_type))){
        x %>% filter(grepl('_filtered', x$peak_type))
      }else{
        x %>% filter(grepl('Target_only_unfiltered', x$peak_type))
      }
    }
  )) %>% 
    dplyr::select(target, sample_group, caller, sample_replicate, npeak) %>% 
    mutate(peak_type = 'each replicate'), 
  dat$nreps %>% 
    dplyr::select(target, sample_group, caller, peak.count) %>% 
    dplyr::rename("npeak" = "peak.count") %>% 
    mutate(peak_type = 'per group', sample_replicate = 'group')
  )
  
  figs[[qc]] <- lapply(
    split(df, df$target), 
    dot_plot2,
    var.x = 'npeak', var.y = 'sample_group', var.color = 'peak_type', add_facet = facet_grid(~caller, scales = 'free'), var.shape = 'peak_type', xlab = 'Peak counts (in thousand)', ylab = '', scale_color = scale_color_manual('', values = c("per group"="indianred", "each replicate"="steelblue")), scale_shape = scale_shape_manual(values = c("per group"=19, "each replicate"=1)), shape = '', plot.title = '', scale_x = 1e-3)
    
  rm(npeaks, df)
}
```

```{r conp_plots}
## plot genomic distributions of consensus peaks ####
qc <- 'conp_ann'
if ( qc %in% names(dat)){
  figs[[qc]] <- mapply(
    bar_plot2,
    MoreArgs = list(var.y = 'genomic.location', xlab = 'Consensus peak count', ylab = ''),
    dat$conp_ann, names(dat$conp_ann),
    SIMPLIFY = F)
  names(figs[[qc]]) <- names(dat$conp_ann)
}

## compare consensus peaks across sample groups ####
qc <- 'rep2conp'
if (qc %in% names(dat)){
  figs[[qc]] <- mapply(
    function(mtx, plot.title){
        shared <- rownames(mtx)[rowSums(mtx)>1]
        df <- reshape2::melt(mtx) %>% 
          filter(value > 0) %>% 
          mutate(
            shared = factor(ifelse(Var1 %in% shared, 'shared', 'unique'), levels = c('unique', 'shared'))
          )
        
        bar_plot(df, var.y = 'Var2', var.fill = 'shared', xlab = 'peak_count', ylab = '', plot.title = plot.title)
     
    },
    dat[[qc]], names(dat[[qc]]), SIMPLIFY = F
  )
    
}
  
## Compare MACS2 and SEACR by consensus peaks ####
  qc <- 'seacr2macs'
if (qc %in% names(dat)){
  
    
  figs[[qc]] <- mapply(
    function(mtx, title){
      if (is.null(mtx)){
        plot_spacer()
      }else if (ncol(mtx) == 1){
        plot_spacer()
      }else{
        venn_plot(mtx, title)
      }
      
      },     
    dat$seacr2macs, names(dat$seacr2macs), 
    SIMPLIFY = F
  )
  
}  

```

```{r dp}

dp.rds <- 'dp.rds'
if (file.exists(dp.rds)){
  dp.list <- readRDS(dp.rds) # by conp, then by cmp
}

if (exists('dp.list')){
  dp_sum <- bind_rows(lapply(dp.list, function(dp){
    bind_rows(lapply(dp, function(x){if(!is.null(x)){x$summary}}))
  })) %>% 
    dplyr::relocate(target, output.folder, control.group, test.group, features.tested:FC.cutoff, control.samples:test.samples)
 
  dp_plots <- lapply(
    dp.list, function(dp){
      mapply(function(idp, prefix){
        y <- idp$y
        df <- idp$df
        out.prefix <- basename(prefix)
        plot.title <- gsub('_vs_', ' vs ', out.prefix)
        list(
          PCA = plot_pca(
            y, 
            out.prefix, 
            color = y$samples$sample_group, 
            sample.label = T, 
            plot.title = "", 
            var.genes = 500, 
            feature.length = "length"),
          MD = plot_MD(
            df, out.prefix = out.prefix, 
            plot.title = plot.title
          ),
          volcano = plot_volcano(
            df, out.prefix = out.prefix, 
            plot.title = plot.title
          )
        )
        
      }, dp, names(dp), SIMPLIFY = F)
    }
  )
  
}
```


```{r fig_setup}

## initiate variables
targets <- sort(setdiff(unique(meta$target), c('IgG', 'Input'))) # targets to make QC plots
ntargets <- length(targets)
ngroups <- length(unique(meta$sample_group))
nsamples <- max(table(meta$target))
  
dim.read <- c(10, ngroups*2 +2)

dim.peak <- c(11, nsamples+1.5)

dim.rep <- c(9, ngroups*0.6+1)

dim.ann <- c(11, ntargets*2+1)
dim.conp <- c(10, ntargets*2+1)

dim.venn <- c(ceiling(sqrt(ntargets))*5, ceiling(ntargets/ceiling(sqrt(ntargets)))*5)

```

## Sample sheet

```{r sample_sheet}

ss %>% 
  select(c(id, sample_group, target, sample_replicate, control)) %>%
  arrange(sample_group, target, sample_replicate) %>% 
  unique.data.frame() %>% 
  DT::datatable(
  class = 'cell-border stripe', 
  rownames = T,  
  filter = 'top', 
  editable = F, 
  extensions = 'Buttons', 
  options = list(
    pageLength = 6, 
    dom = 'Bfrtip',
    buttons = c('csv')
  ))

```

## {.unnumbered .unlisted}

$$\\[0.5in]$$





