

## {.unnumbered .unlisted}

$$\\[0.5in]$$


## Differential peaks (DP)


### DP Summary

```{r }
if (exists('dp_sum')){
dp_sum %>% 
  DT::datatable(
  class = 'cell-border stripe', 
  rownames = T,  
  filter = 'top', 
  editable = F, 
  extensions = 'Buttons', 
  options = list(
    pageLength = 6, 
    dom = 'Bfrtip',
    buttons = c('csv')
  ))
}
```

$$\\[0.2in]$$

### DP plots {.tabset .tabset-pills}

```{r results='asis', fig.cap=c('Fig. Differential expression analysis. (A) PCA plot. (B) MA/MD plot. (C) Volcano plot'), fig.width=12, fig.height=5}
if (exists('dp_plots')){
for (tgt in targets){
  cat ('####', tgt, '{.tabset .tabset-pills}\n\n') # target level
  
  cnp <- grep(tgt, names(dp_plots), value = T)
  
  if (length(cnp) > 0){
    for (i in cnp){ # conp level
      cat ('#####', i, '{.tabset .tabset-pills}\n\n') 
      cnp_dp <- dp_plots[[i]] 
      cnp_dp[sapply(cnp_dp, is.null)] <- NULL
      for (j in 1:length(cnp_dp)){ # cmp level
        p <- wrap_plots(cnp_dp[[j]], nrow = 1) + plot_annotation(tag_levels = 'A')
        
        make_tabs(
          paste("######", names(cnp_dp)[j]),
          list(p)
        )
      }
    }
  }
}

}
```

## {.unnumbered .unlisted}

$$\\[0.5in]$$


