
## Methods

(Tool references are provided as hyperlinks.)

Trim Galore (https://github.com/FelixKrueger/TrimGalore) was used to examine read quality and trim adapters.
Reads were aligned to the reference genome using [Bowtie2](https://www.nature.com/articles/nmeth.1923).
Genome coverage profiles were generated using [bedtools genomecov](https://academic.oup.com/bioinformatics/article/26/6/841/244688).
Both [MACS2](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2008-9-9-r137) and [SEACR](https://doi.org/10.1186/s13072-019-0287-4) were used to call peaks from a sample.
IgG reads were deduplicated using [GATK MarkDuplicates](http://dx.doi.org/10.1101/gr.107524.110).
MACS2 was run in both target-only and IgG-controlled (using all IgG reads) modes.
For narrow peaks used for TFs and some histone marks (e.g. H3K4me3), IgG-controlled peaks were kept for downstream analysis if they meet the following criteria: overlapping with treatment-only peaks, q-value \< 0.01 and enrichment \> 2. For broad peaks used for some histone marks (e.g. H3K27me3) and proteins targeting broad domains, target-only peaks were kept for downstream analysis if they meet the follow criteria: overlapping with IgG-controlled peaks, q-value \< 0.01 and enrichment \> 2.
SEACR was run with IgG normalization (using deduplicated reads) and with top 1% of peaks reported, both in stringent mode. IgG-normalized peaks that overlap with top 1% of peaks were kept for further analysis.

For each target, differential peaks between two groups were detected using Bioconductor package [edgeR 3.36.0](https://academic.oup.com/bioinformatics/article/26/1/139/182458).
Frist, replicated peaks were generated by merging peaks called from individual samples and keeping those present in at least 2 replicates. Next consensus peaks were generated by merging replicated peaks across all sample groups. For a comparison between two groups, consensus peaks present in either group were filtered by edgeR function filterByExpr with min.count = 10 and min.total.count = 15. The resultant count matrix was normalized using [TMM method](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25) and subject to significance testing with generalized linear models and quasi-likelihood method. Peaks were deemed significantly differential by the thresholds described in section **Differential Peaks**.

## {.unnumbered .unlisted}

$$\\[0.5in]$$


## Acknowledgement

(For publication, please include the following acknowledgement) This research was supported by the Genomics & Bioinformatics Shared Resource of the Fred Hutch/University of Washington/Seattle Children's Cancer Consortium ([P30 CA015704](https://www.cancerconsortium.org/about.html)).

## {.unnumbered .unlisted}

$$\\[0.5in]$$
